---
apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - image: pradiph31/book-service
          name: book-service
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - image: pradiph31/review-service
          name: review-service
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composite-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composite-service
  template:
    metadata:
      labels:
        app: composite-service
    spec:
      containers:
        - env:
            - name: BOOK_SERVICE_URL
              value: http://book-service:8080
            - name: REVIEW_SERVICE_URL
              value: http://review-service:8080
          image: pradiph31/composite-service:2.0.0
          name: composite-service
          ports:
            - containerPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: composite-service-hpa
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: composite-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: review-service-hpa
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: review-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: book-service-hpa
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: book-service

---

apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: default
spec:
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: default
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: composite-service
  namespace: default
spec:
  selector:
    app: composite-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

